{
 "title": "demo dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "log_filter", "label": "Log Filter" }
  ]
 },
 "panels": [
  {
   "title": "Request Log",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "desc",
     "expr": "_stream:{service.name=\"demo\"} \n| fields tenantId, requestId, request.method, request.uri, request.body, response.status, response.took, response.body"
    }
   ]
  },
  {
   "title": "p95 latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method, uri, status) (rate(http.server.requests_bucket{uri!=\"/actuator/health\"}[1m])))",
     "legendFormat": "[{{method}}] {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, uri, status) (rate(http.server.requests_bucket{status=~\"4..|5..\"}[$__rate_interval]))",
     "legendFormat": "[{{method}}] {{uri}} - {{status}}"
    }
   ]
  }
 ]
}